### PR TITLE
Sixel Part 2. Ignore embedded by Windows CSI and OSC sequences.

### LINKED ISSUE #5: Determine why Sixel VT escape sequences are not being processed on Windows
**Describe the bug**
The windows build is either not receiving Sixel VT escape sequences properly or is not able to properly interpret them. (this may apply to other escape sequences as well)

**To Reproduce**
1. Start aminal.exe on windows (currently requires the shell to be specified by cli parameter `aminal --shell cmd.exe`)
2. Output the contents of example.sixel to the tty `type example.sixel`

**Expected behavior**
The test image should display in the terminal window.

**Observed behavior**
A large quantity of text is displayed in the terminal window.

**Screenshots**
image
image

**Environment:**
 - Windows 10 v.1809

**Additional context**

**Logs**
I'm not currently able to capture a debug log on windows due to what seems to be a misbehavior in the operating system when combining output pipes and ConPTY API hosts (I get the output from the guest processes but not the host).

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #5

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Start `aminal` and `type example.sixel`.
In most cases it displays the image, though corrupted.

In debug mode, it also prints sixel lines as they were received from the Windows pty with embedded CSI and OSC sequences.

**Test Configuration**:
* OS: Windows 10
* OS version: 1809
* Go version: 1.11

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MaxRis** [comment]
@rrrooommmaaa I still can't get `type example.sixel` to display the image.
Should be there some extra steps to make it work?

I also was not able to see that the added checks `			if t == '[' { // Windows injected a CSI sequence, let's ignore it` and `			if t == ']' { // Windows injected an OCS sequence, let's ignore it` returns `true` at some point.

**Comment by rrrooommmaaa** [comment]
@MaxRis I'm preparing another update this weekend that will solve some issues.

**Comment by nikitar020** [comment]
Should we wait and merge all the functionality as a single PR? Just because this PR does not actually fix #5 and does not contain any visible changes to the Aminal functionality.

**Comment by MaxRis** [comment]
Superseded by https://github.com/liamg/aminal/pull/132

**Pull request closed without merging**
